### ISSUE TITLE
Removing package breaks committing.

### ISSUE THREAD

**Issue by tormi** [wunderio/code-quality#22]
Looks like there are some issues when trying to remove the package. Removed it from Composer, but got this when tried to commit afterwards:

`Git: .git/hooks/pre-commit: line 15: path/to/vendor/bin/grumphp: No such file or directory`

**Comment by tormi** [comment]
`less .git/hooks/pre-commit`: 

```
...

# Grumphp env vars
export GRUMPHP_GIT_WORKING_DIR=$(git rev-parse --show-toplevel)

# Run GrumPHP
(cd "./" && printf "%s\n" "${DIFF}" | 'exec' './vendor/bin/grumphp' 'git:pre-commit' '--skip-success-output')
```

**Comment by tormi** [comment]
Also,

`Git: .git/hooks/commit-msg: line 19: path/to/vendor/bin/grumphp: No such file or directory`

**Comment by tormi** [comment]
`less .git/hooks/commit-msg`:

```
...

# Grumphp env vars
export GRUMPHP_GIT_WORKING_DIR=$(git rev-parse --show-toplevel)

# Run GrumPHP
(cd "./" && printf "%s\n" "${DIFF}" | 'exec' './vendor/bin/grumphp' 'git:commit-msg' "--git-user=$GIT_USER" "--git-email=$GIT_EMAIL" "$COMMIT_MSG_FILE")

```

**Comment by guncha25** [comment]
It looks like feature is implemented - https://github.com/phpro/grumphp/blob/master/src/Composer/GrumPHPPlugin.php#L71 but testing it - event is never fired. Since this is more of Composer/GrumPHP issue i am closing this as we can not control grumPHP. This issue should be added to GrumPHP. 
Otherwise you can always run `vendor/bin/grumphp git:deinit` and make git hooks disappear before removing this tool.

**Comment by tormi** [comment]
Thanks for the `git:deinit` tip!
