### ISSUE TITLE
Improve run command execution.

### ISSUE THREAD

**Issue by guncha25** [wunderio/code-quality#6]
Current run functionality is not processing files correctly. 

One way to fix this could be custom tasks that would handle this better.

**Comment by hkirsman** [comment]
GrumPHP is adding all files separately to each command so while 10 commited files might be ok, 3000 files are hitting limit on how long your command can be.
Here https://github.com/wunderio/grumphp-php-compatibility/pull/3/files I fixed it like this:
https://github.com/wunderio/grumphp-php-compatibility/pull/3/files - it detects if command is run and then instead of adding all files, it just adds 1 folder to the end of command (phpcs ... folder/to/scan)

**Comment by hkirsman** [comment]
Also I noticed that even running 1 tester can take quite a long time so we might need to separate local tests and the ones that are run on Silta.
